default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
